[package]
name = "mempool-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.29.2
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde-json = "1.0"
tokio = { version = "1", features = ["full"] }